# Generated by Django 4.1.7 on 2023-03-12 14:32

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bureau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=16, unique=True, verbose_name="名称"),
                ),
                (
                    "keyword",
                    models.SlugField(
                        help_text="英数字と-が利用できます。URLに使用される文字列です。",
                        unique=True,
                        verbose_name="キーワード",
                    ),
                ),
                (
                    "outline",
                    markdownx.models.MarkdownxField(
                        help_text="マークダウン形式で入力してください。", verbose_name="局概要"
                    ),
                ),
                (
                    "sort_num",
                    models.SmallIntegerField(
                        help_text="整数を入力してください。値が小さいほど上に表示されます。", verbose_name="ソート値"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最終更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bureau_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bureau_updater",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bureaus",
            },
        ),
    ]
