# Generated by Django 4.1.7 on 2023-03-12 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_alter_bureau_created_by_alter_bureau_updated_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bureau",
            options={"verbose_name": "局", "verbose_name_plural": "局リスト"},
        ),
        migrations.AlterField(
            model_name="bureau",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bureau_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作成者",
            ),
        ),
        migrations.AlterField(
            model_name="bureau",
            name="updated_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bureau_updater",
                to=settings.AUTH_USER_MODEL,
                verbose_name="最終更新者",
            ),
        ),
    ]
