# Generated by Django 4.1.7 on 2023-03-11 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_account_email"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="account",
            table="accounts",
        ),
    ]
