# Generated by Django 4.1.7 on 2023-03-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_account_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最終ログイン日時"),
        ),
    ]
